Wen dev
lmitechnologies/new_engagement_template pull request #4
Opened 2022-11-14 15:38 UTC by fanchuanster

2022-11-14 19:18 UTC, trevorditrani requested changes

2022-11-14 19:43 UTC, fanchuanster commented on gadgetapp/inspection/views.py
> +                    logging.warning(f'Key error for decision JSON field: {index} {e} {CHART_KEYS[index]}. Assigned default decison: {AVAILABLE_DECISIONS[0]}')
removed e

2022-11-14 19:44 UTC, fanchuanster commented on gadgetapp/inspection/views.py
> +                    logging.warning(f'Key error for decision JSON field: {index} {e} {CHART_KEYS[index]}. Assigned default decison: {AVAILABLE_DECISIONS[0]}')
rectified.

2022-11-15 14:58 UTC, trevorditrani approved these changes

2022-11-15 14:59 UTC, merged